name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout

        uses: actions/checkout@v4
      - name: Install Python dependencies
        run: |
          pip install pipenv
          pipenv install --deploy --system
      - name: Install Cypress dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: python api/app.py
          wait-on: 'http://localhost:5000'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
